services:
  - type: web
    name: Auto-Approve-Bot-render
    runtime: docker
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CHID
        sync: false
      - key: FSUB
        sync: false
      - key: SUDO
        sync: false
